// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADkQT7r7WnrVVFMpIu921Nkz1i82y98iE',
    appId: '1:785213934210:web:4752a70611c1797932829b',
    messagingSenderId: '785213934210',
    projectId: 'gongsan-ddf1c',
    authDomain: 'gongsan-ddf1c.firebaseapp.com',
    storageBucket: 'gongsan-ddf1c.appspot.com',
    measurementId: 'G-DLMN3SHK28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmL7aEnmzvpRxC_xLcKI4zDF13yfj8NAw',
    appId: '1:785213934210:android:6e7f74f2ecbe801832829b',
    messagingSenderId: '785213934210',
    projectId: 'gongsan-ddf1c',
    storageBucket: 'gongsan-ddf1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMaB5qEL_rR0CmrvUT3sXEHVFVgxTUb3c',
    appId: '1:785213934210:ios:8659971dc80b024c32829b',
    messagingSenderId: '785213934210',
    projectId: 'gongsan-ddf1c',
    storageBucket: 'gongsan-ddf1c.appspot.com',
    iosBundleId: 'com.example.gongsan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMaB5qEL_rR0CmrvUT3sXEHVFVgxTUb3c',
    appId: '1:785213934210:ios:8c6734c4d26319b332829b',
    messagingSenderId: '785213934210',
    projectId: 'gongsan-ddf1c',
    storageBucket: 'gongsan-ddf1c.appspot.com',
    iosBundleId: 'com.example.gongsan.RunnerTests',
  );
}
